spring:
  application:
    name: Washer-Backend-v2
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: -1ms
  security:
    cors:
      allowed-origins:
        - 'http://localhost:3000'
        - 'http://localhost:3001'
  docker:
    compose:
      enabled: false
server:
  port: 8080
  shutdown: graceful
third-party:
  discord:
    webhook-url: ${THIRD_PARTY_DISCORD_WEBHOOK_URL}
springdoc:
  swagger-ui:
    config-url: "/v3/api-docs/swagger-config"
    urls:
      - name: "Washer-Backend-v2 API"
        url: "/v3/api-docs"
    operationsSorter: "method"
    defaultModelsExpandDepth: -1
    docExpansion: "none"
    displayRequestDuration: true
    filter: true
    showCommonExtensions: true
    showExtensions: true
    deepLinking: true
    persistAuthorization: true
    tryItOutEnabled: true
    validatorUrl: ""
    csrf:
      enabled: false
